# Generated by Django 5.2.9 on 2025-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('school', models.CharField(max_length=50)),
                ('casting_time', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('components', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('concentration', models.CharField(max_length=50)),
                ('ritual', models.BooleanField()),
            ],
        ),
    ]
