# Generated by Django 5.2.9 on 2025-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hit_die', models.CharField(max_length=50)),
                ('primary_ability', models.CharField(max_length=50)),
                ('saving_throws', models.JSONField(default=list)),
                ('armor_proficiencies', models.JSONField(default=list)),
                ('weapon_proficiencies', models.JSONField(default=list)),
                ('tool_proficiencies', models.JSONField(default=list)),
                ('skills_available', models.JSONField(default=list)),
                ('spellcasting', models.BooleanField(default=False)),
                ('archetypes', models.JSONField(default=list)),
                ('short_description', models.TextField(default='To be uncovered...')),
                ('source_book', models.CharField(default='Unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=50)),
                ('description', models.TextField(default='To be uncovered...')),
                ('source_book', models.CharField(default='Unknown', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='To be uncovered...')),
                ('traits', models.JSONField(default=list)),
                ('source_book', models.CharField(default='Unknown', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='source_book',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(default='To be uncovered...'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
