# Generated by Django 5.2.9 on 2025-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_class_magicitem_specie_spell_source_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='attack_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='spell',
            name='damage',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='spell',
            name='higher_level',
            field=models.TextField(default='To be uncovered...'),
        ),
        migrations.AddField(
            model_name='spell',
            name='material',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_type',
            field=models.CharField(default='Support', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.JSONField(default=list),
        ),
    ]
