# Generated by Django 5.2.9 on 2025-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_spell_attack_type_spell_damage_spell_higher_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='concentration_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='hit_die',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='attack_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='concentration',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='spell',
            name='material',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spell_type',
            field=models.CharField(default='To be uncovered...', max_length=50),
        ),
    ]
